export const ErrorCode = {
  SUCCESS: 0,
  VALIDATION_FAILED: 40001,
  INVALID_CREDENTIALS: 40101,
  USER_DISABLED: 40102,
  TOKEN_EXPIRED: 40103,
  TOKEN_INVALID: 40104,
  TOKEN_REVOKED: 40105,
  TOKEN_REUSE_DETECTED: 40106,
  USER_ALREADY_EXISTS: 40901,
  CONVERSATION_NOT_FOUND: 40401,
  ATTACHMENT_NOT_FOUND: 40402,
  AI_MODEL_NOT_FOUND: 40010,
  UPLOAD_TYPE_NOT_ALLOWED: 40011,
  UPLOAD_TEXT_EXTRACT_FAILED: 40012,
  UPLOAD_TOO_LARGE: 41301,
  AI_RATE_LIMITED: 42901,
  AI_CONCURRENT_STREAM_LIMIT: 42902,
  AI_PROVIDER_ERROR: 50201,
  INTERNAL_SERVER_ERROR: 50001,
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorMessages: Record<ErrorCodeType, string> = {
  [ErrorCode.SUCCESS]: 'success',
  [ErrorCode.VALIDATION_FAILED]: '请求参数校验失败',
  [ErrorCode.INVALID_CREDENTIALS]: '用户名/邮箱或密码错误',
  [ErrorCode.USER_DISABLED]: '用户账号已被封禁或注销',
  [ErrorCode.TOKEN_EXPIRED]: 'Access Token 已过期',
  [ErrorCode.TOKEN_INVALID]: 'Token 签名非法或格式无效',
  [ErrorCode.TOKEN_REVOKED]: 'Token 已被注销或列入黑名单',
  [ErrorCode.TOKEN_REUSE_DETECTED]: '检测到已作废的 Refresh Token 重放，触发安全防护清除全量会话',
  [ErrorCode.USER_ALREADY_EXISTS]: '用户名或邮箱已被注册占用',
  [ErrorCode.CONVERSATION_NOT_FOUND]: '会话不存在或不属于当前用户',
  [ErrorCode.ATTACHMENT_NOT_FOUND]: '附件不存在或不属于当前用户',
  [ErrorCode.AI_MODEL_NOT_FOUND]: '指定的 AI 模型不存在或未启用',
  [ErrorCode.UPLOAD_TYPE_NOT_ALLOWED]: '文件类型不在支持的白名单中',
  [ErrorCode.UPLOAD_TEXT_EXTRACT_FAILED]: '文档文本提取失败，无法解析内容',
  [ErrorCode.UPLOAD_TOO_LARGE]: '上传文件超出最大限制大小',
  [ErrorCode.AI_RATE_LIMITED]: '请求频率超出上限，请稍后再试',
  [ErrorCode.AI_CONCURRENT_STREAM_LIMIT]: '同时进行的 AI 对话流超出上限',
  [ErrorCode.AI_PROVIDER_ERROR]: 'AI 供应商上游服务异常或响应错误',
  [ErrorCode.INTERNAL_SERVER_ERROR]: '服务器内部未知异常',
};
